/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'businesses-create': RouteRecordInfo<'businesses-create', '/businesses/create', Record<never, never>, Record<never, never>>,
    'businesses-edit-id': RouteRecordInfo<'businesses-edit-id', '/businesses/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'businesses-list': RouteRecordInfo<'businesses-list', '/businesses/list', Record<never, never>, Record<never, never>>,
    'businesses-view-id': RouteRecordInfo<'businesses-view-id', '/businesses/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'clients-create': RouteRecordInfo<'clients-create', '/clients/create', Record<never, never>, Record<never, never>>,
    'clients-edit-id': RouteRecordInfo<'clients-edit-id', '/clients/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'clients-list': RouteRecordInfo<'clients-list', '/clients/list', Record<never, never>, Record<never, never>>,
    'clients-view-id': RouteRecordInfo<'clients-view-id', '/clients/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'companies-bin': RouteRecordInfo<'companies-bin', '/companies/bin', Record<never, never>, Record<never, never>>,
    'companies-create': RouteRecordInfo<'companies-create', '/companies/create', Record<never, never>, Record<never, never>>,
    'companies-edit-id': RouteRecordInfo<'companies-edit-id', '/companies/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'companies-list': RouteRecordInfo<'companies-list', '/companies/list', Record<never, never>, Record<never, never>>,
    'companies-view-id': RouteRecordInfo<'companies-view-id', '/companies/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'dashboards-administrator': RouteRecordInfo<'dashboards-administrator', '/dashboards/administrator', Record<never, never>, Record<never, never>>,
    'dashboards-client-dash': RouteRecordInfo<'dashboards-client-dash', '/dashboards/client_dash', Record<never, never>, Record<never, never>>,
    'dashboards-employee-dash': RouteRecordInfo<'dashboards-employee-dash', '/dashboards/employee_dash', Record<never, never>, Record<never, never>>,
    'fee-notes-create': RouteRecordInfo<'fee-notes-create', '/fee_notes/create', Record<never, never>, Record<never, never>>,
    'fee-notes-list': RouteRecordInfo<'fee-notes-list', '/fee_notes/list', Record<never, never>, Record<never, never>>,
    'fee-notes-summary-client-client-summary': RouteRecordInfo<'fee-notes-summary-client-client-summary', '/fee_notes/summary/client/client_summary', Record<never, never>, Record<never, never>>,
    'fee-notes-summary-client-details-id': RouteRecordInfo<'fee-notes-summary-client-details-id', '/fee_notes/summary/client/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'fee-notes-summary-company-company-summary': RouteRecordInfo<'fee-notes-summary-company-company-summary', '/fee_notes/summary/company/company_summary', Record<never, never>, Record<never, never>>,
    'fee-notes-summary-company-details-id': RouteRecordInfo<'fee-notes-summary-company-details-id', '/fee_notes/summary/company/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'files-client-create': RouteRecordInfo<'files-client-create', '/files/client/create', Record<never, never>, Record<never, never>>,
    'files-client-list': RouteRecordInfo<'files-client-list', '/files/client/list', Record<never, never>, Record<never, never>>,
    'files-client-view-id': RouteRecordInfo<'files-client-view-id', '/files/client/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'hrm-employees-create': RouteRecordInfo<'hrm-employees-create', '/hrm/employees/create', Record<never, never>, Record<never, never>>,
    'hrm-employees-edit-id': RouteRecordInfo<'hrm-employees-edit-id', '/hrm/employees/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'hrm-employees-list': RouteRecordInfo<'hrm-employees-list', '/hrm/employees/list', Record<never, never>, Record<never, never>>,
    'hrm-payroll-payroll': RouteRecordInfo<'hrm-payroll-payroll', '/hrm/payroll/payroll', Record<never, never>, Record<never, never>>,
    'hrm-payroll-payslip-id': RouteRecordInfo<'hrm-payroll-payslip-id', '/hrm/payroll/payslip/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'hrm-payroll-salary-update': RouteRecordInfo<'hrm-payroll-salary-update', '/hrm/payroll/salary_update', Record<never, never>, Record<never, never>>,
    'hrm-reports-employee-report': RouteRecordInfo<'hrm-reports-employee-report', '/hrm/reports/employee_report', Record<never, never>, Record<never, never>>,
    'hrm-reports-report': RouteRecordInfo<'hrm-reports-report', '/hrm/reports/report', Record<never, never>, Record<never, never>>,
    'invoices-list': RouteRecordInfo<'invoices-list', '/invoices/list', Record<never, never>, Record<never, never>>,
    'invoices-payment-id': RouteRecordInfo<'invoices-payment-id', '/invoices/payment/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'invoices-view-id': RouteRecordInfo<'invoices-view-id', '/invoices/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'obligations-create': RouteRecordInfo<'obligations-create', '/obligations/create', Record<never, never>, Record<never, never>>,
    'obligations-edit-id': RouteRecordInfo<'obligations-edit-id', '/obligations/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'obligations-list': RouteRecordInfo<'obligations-list', '/obligations/list', Record<never, never>, Record<never, never>>,
    'roles': RouteRecordInfo<'roles', '/roles', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'services-create': RouteRecordInfo<'services-create', '/services/create', Record<never, never>, Record<never, never>>,
    'services-edit-id': RouteRecordInfo<'services-edit-id', '/services/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'services-list': RouteRecordInfo<'services-list', '/services/list', Record<never, never>, Record<never, never>>,
    'tasks-create': RouteRecordInfo<'tasks-create', '/tasks/create', Record<never, never>, Record<never, never>>,
    'tasks-list': RouteRecordInfo<'tasks-list', '/tasks/list', Record<never, never>, Record<never, never>>,
    'users-create': RouteRecordInfo<'users-create', '/users/create', Record<never, never>, Record<never, never>>,
    'users-edit-id': RouteRecordInfo<'users-edit-id', '/users/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'users-list': RouteRecordInfo<'users-list', '/users/list', Record<never, never>, Record<never, never>>,
  }
}
